### ISSUE TITLE
UnicodeDecodeError

### ISSUE THREAD

**Issue by AhmetAciksari46** [martin-ger/esp_wifi_repeater#392]
When i click the Start button, giving error;
Traceback (most recent call last):
  File "download_panel_info.py", line 448, in OnButton_StartButton
  File "download_panel_info.py", line 421, in start_func
  File "download_panel_info.py", line 703, in flash_config
UnicodeDecodeError: 'gb2312' codec can't decode bytes in position 28-29: illegal multibyte sequence

**Comment by martin-ger** [comment]
Actually, I have no idea. What did you try to do/click?
